# Generated by Django 5.2.7 on 2026-03-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('session', '0002_alter_session_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='role.role'),
        ),
    ]
