# Generated by Django 5.2.1 on 2025-08-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
