# Generated by Django 5.2.6 on 2025-09-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
