# Generated by Django 5.2.7 on 2026-03-13 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('actor', 'Actor'), ('agent', 'Agent'), ('casting_director', 'Casting Director')], default='actor', max_length=20),
        ),
        migrations.CreateModel(
            name='CastingDirectorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='', upload_to='uploads/casting_directors')),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='casting_director_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
