services:
  web:
    build: ./nikabond_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./nikabond_backend/:/usr/src/nikabond_backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SQL_PASSWORD
      - POSTGRES_DB=nikabond
volumes:
  postgres_data:
