# Generated by Django 5.2.6 on 2025-09-03 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/agents')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default=None, max_length=255)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('phone', models.CharField(default=None, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
