# Generated by Django 5.2.6 on 2025-09-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agency',
        ),
    ]
