# Generated by Django 5.2.7 on 2026-03-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0005_alter_actor_agent'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='roles', to='actor.actor'),
        ),
    ]
