# Generated by Django 5.2.7 on 2026-03-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_role_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='uploads/roles'),
        ),
    ]
