# Generated by Django 5.2.1 on 2025-07-22 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/actors')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('haircolor', models.CharField(max_length=255)),
                ('hairstyle', models.CharField(max_length=255)),
                ('eyecolor', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('other', 'Other')], default=None, max_length=50, null=True)),
                ('ethnicity', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('other', 'Other')], default=None, max_length=50, null=True)),
                ('info', models.TextField(max_length=255)),
                ('experience', models.TextField(max_length=255)),
                ('skills', models.TextField(max_length=255)),
                ('occupations', models.TextField(max_length=255)),
                ('languages', models.TextField(max_length=255)),
                ('residence', models.TextField(max_length=255)),
                ('licence', models.TextField(max_length=255)),
                ('height', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
