# Generated by Django 5.2.4 on 2025-08-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="residence",
        ),
        migrations.AddField(
            model_name="actor",
            name="country",
            field=models.CharField(default="UNK", max_length=255),
        ),
        migrations.AddField(
            model_name="actor",
            name="country_code",
            field=models.CharField(default="XX", max_length=255),
        ),
        migrations.AddField(
            model_name="actor",
            name="dob",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="actor",
            name="email",
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name="actor",
            name="gender_other",
            field=models.CharField(
                blank=True,
                help_text="If you selected Other, you can specify here.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="actor",
            name="phone",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name="actor",
            name="description",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="actor",
            name="ethnicity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("nonbinary", "Non-binary"),
                    ("other", "Other"),
                    ("no_answer", "prefer not to say"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="experience",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="actor",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("nonbinary", "Non-binary"),
                    ("other", "Other"),
                    ("no_answer", "prefer not to say"),
                ],
                default="no_answer",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="info",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="actor",
            name="languages",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="actor",
            name="licence",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="actor",
            name="occupations",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="actor",
            name="skills",
            field=models.CharField(max_length=255),
        ),
    ]
