# Generated by Django 5.2.1 on 2025-08-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_remove_actor_residence_actor_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
