# Generated by Django 5.2.4 on 2025-08-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actor", "0003_alter_actor_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="citizenship",
            field=models.CharField(default="unk", max_length=100),
        ),
        migrations.AddField(
            model_name="actor",
            name="cwh",
            field=models.CharField(default="unk", max_length=100),
        ),
        migrations.AddField(
            model_name="actor",
            name="shoe_size",
            field=models.CharField(default="unk", max_length=100),
        ),
        migrations.AddField(
            model_name="actor",
            name="size",
            field=models.CharField(default="unk", max_length=100),
        ),
        migrations.AddField(
            model_name="actor",
            name="work_permits",
            field=models.CharField(default="unk", max_length=100),
        ),
        migrations.AlterField(
            model_name="actor",
            name="ethnicity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("black", "Black"),
                    ("white", "White"),
                    ("asian", "Asian"),
                    ("other", "Other"),
                    ("no_answer", "prefer not to say"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
    ]
