# Generated by Django 5.2.6 on 2025-09-04 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0004_actor_citizenship_actor_cwh_actor_shoe_size_and_more'),
        ('agent', '0002_remove_agent_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors', to='agent.agent'),
        ),
    ]
