# Generated by Django 5.2.7 on 2026-03-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0005_alter_actor_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='uploads/actors'),
        ),
    ]
