# Generated by Django 5.2.6 on 2025-09-05 12:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/projects')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default=None, max_length=255)),
                ('shooting_start', models.DateField()),
                ('shooting_end', models.DateField()),
                ('callback_start', models.DateField()),
                ('callback_end', models.DateField()),
                ('tryons_start', models.DateField()),
                ('tryons_end', models.DateField()),
                ('rehearsal_start', models.DateField()),
                ('rehearsal_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
