# Generated by Django 5.2.7 on 2026-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='author_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
